{% set name = "igwn-auth-utils" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: b6964ef56692fe6e7279aa4b18c68d069a4e2b9e42a6b237d89e780c1b093a24

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=69.3.0
    - setuptools-scm >=3.4.3
    - wheel
  run:
    - cryptography >=3.2
    - python >={{ python_min }}
    - requests >=2.20
    - safe-netrc >=1.0.0
    - scitokens >=1.8.0

test:
  requires:
    - pip
    - pytest >=3.9.1
    - python {{ python_min }}
    - requests-mock
  commands:
    # check requirements
    - python -m pip check
    - python -m pip show igwn-auth-utils
    # run test suite
    - python -m pytest --pyargs igwn_auth_utils.tests

about:
  home: https://igwn-auth-utils.readthedocs.io
  dev_url: https://git.ligo.org/computing/igwn-auth-utils.git
  doc_url: https://igwn-auth-utils.readthedocs.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Authorisation utilities for IGWN
  description: |
    Python library functions to simplify using IGWN authorisation credentials.

    This project is primarily aimed at discovering X.509 credentials and
    SciTokens for use with HTTP(S) requests to IGWN-operated services.

extra:
  recipe-maintainers:
    - duncanmmacleod
