{% set name = "igwn-auth-utils" %}
{% set version = "1.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 0addd3f8d247c2c68de7cd328265968de1d3912a9150871f36ad7354165d2a57

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=70.0.0
    - setuptools-scm >=3.4.3
    - wheel
  run:
    - __unix  # [unix]
    - __win  # [win]
    - cryptography >=44.0.1
    - htgettoken >=2.1  # [unix]
    - python >={{ python_min }}
    - python-gssapi >=1.9.0
    - requests >=2.32.0
    - safe-netrc >=1.0.0
    - scitokens >=1.8.0

test:
  requires:
    - pip
    - pytest >=3.9.1
    - python {{ python_min }}
    - requests-mock
  commands:
    # check requirements
    - python -m pip check
    - python -m pip show igwn-auth-utils
    # run test suite
    - python -m pytest --pyargs igwn_auth_utils.tests  # [unix]
    - python -m pytest --pyargs igwn_auth_utils.tests -k "not test_kerberos and not test_get_token"  # [win]

about:
  home: https://igwn-auth-utils.readthedocs.io
  dev_url: https://git.ligo.org/computing/software/igwn-auth-utils.git
  doc_url: https://igwn-auth-utils.readthedocs.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Authorisation utilities for IGWN
  description: |
    Python library functions to simplify using IGWN authorisation credentials.

    This project is primarily aimed at discovering X.509 credentials and
    SciTokens for use with HTTP(S) requests to IGWN-operated services.

extra:
  recipe-maintainers:
    - duncanmmacleod
