{% set name = "igwn-auth-utils" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 17ea61ef47dd642a572e887f37f5181613d8882ed4b917b1279cdb188859de3c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools >=38.2.5
    - setuptools-scm
    - wheel
  run:
    - cryptography >=2.3
    - scitokens >=1.7.0
    - python >=3.6
  run_constrained:
    - requests >=2.14
    - safe_netrc >=1.0.0

test:
  requires:
    - pip
    - pytest >=3.6.3
    - requests
    - requests-mock
    - safe-netrc
  commands:
    - python -m pip check
    - python -m pytest --pyargs igwn_auth_utils.tests

about:
  home: https://igwn-auth-utils.readthedocs.io
  dev_url: https://git.ligo.org/computing/igwn-auth-utils.git
  doc_url: https://igwn-auth-utils.readthedocs.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Authorisation utilities for IGWN
  description: |
    Python library functions to simplify using IGWN authorisation credentials.

    This project is primarily aimed at discovering X.509 credentials and
    SciTokens for use with HTTP(S) requests to IGWN-operated services.

extra:
  recipe-maintainers:
    - duncanmmacleod
